#!/bin/sh

cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

./src/Allwmake

wmake  ./applications/utilities/preProcessing/canteraToFPVCentralFoam
wmake  ./applications/utilities/postProcessing/FPVCentralFoamPost
wmake  ./applications/solver/FPVCentralFoam

# ----------------------------------------------------------------- end-of-file
